version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    command:
      - /bin/bash
      - -c
      - |
        [ -d vendor/bin ] || composer install
        [ -f .env ] || { cp .env.example .env; php artisan key:generate --ansi; }
        apache2-foreground

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql:cached

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

volumes:
  db:
    driver: local
